using System;

namespace KeybindsPlus.Models
{
    public enum ChatChannels : int
    {
        Say,
        Yell,
        Shout,
        Party,
        Alliance,
        FreeCompany,
        PvpTeam,
        NoviceNetwork,
        NextCrossworldLinkshell, PreviousCrossworldLinkshell,
        NextLinkshell, PreviousLinkshell,
        Linkshell1, Linkshell2, Linkshell3, Linkshell4,
        Linkshell5, Linkshell6, Linkshell7, Linkshell8,
        CrossWorldLinkshell1, CrossWorldLinkshell2, CrossWorldLinkshell3, CrossWorldLinkshell4,
        CrossWorldLinkshell5, CrossWorldLinkshell6, CrossWorldLinkshell7, CrossWorldLinkshell8,

        // Temporary Channel Switches
        TemporarySay,
        TemporaryYell,
        TemporaryShout,
        TemporaryParty,
        TemporaryAlliance,
        TemporaryFreeCompany,
        TemporaryPvpTeam,
        TemporaryNoviceNetwork,
        TemporaryNextCrossworldLinkshell, TemporaryPreviousCrossworldLinkshell,
        TemporaryNextLinkshell, TemporaryPreviousLinkshell,
        TemporaryLinkshell1, TemporaryLinkshell2, TemporaryLinkshell3, TemporaryLinkshell4,
        TemporaryLinkshell5, TemporaryLinkshell6, TemporaryLinkshell7, TemporaryLinkshell8,
        TemporaryCrossWorldLinkshell1, TemporaryCrossWorldLinkshell2, TemporaryCrossWorldLinkshell3,
        TemporaryCrossWorldLinkshell4, TemporaryCrossWorldLinkshell5, TemporaryCrossWorldLinkshell6,
        TemporaryCrossWorldLinkshell7, TemporaryCrossWorldLinkshell8,

        // Tell Channels
        ReplyForward,
        TemporaryReplyForward,
        ReplyBack, // TODO: Implement ReplyBack functionality
        TemporaryReplyBack, // TODO: Implement TemporaryReplyBack functionality
    }
    public static class ChatChannelExtensions
    {
        public static ActionMetadata GetMetadata(this ChatChannels channel) => channel switch
        {
            ChatChannels.TemporaryReplyForward => new ActionMetadata("Reply Temporarily", ActionCategory.Chat, false, "Implementing Tells via ClientStructs are a pain."),
            ChatChannels.TemporaryReplyBack => new ActionMetadata("Reply (Back) Temporarily", ActionCategory.Chat, false, "Implementing Tells via ClientStructs are a pain."),
            ChatChannels.TemporarySay => new ActionMetadata("Temporarily Switch Chat Mode to Say", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryYell => new ActionMetadata("Temporarily Switch Chat Mode to Yell", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryShout => new ActionMetadata("Temporarily Switch Chat Mode to Shout", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryParty => new ActionMetadata("Temporarily Switch Chat Mode to Party", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryAlliance => new ActionMetadata("Temporarily Switch Chat Mode to Alliance", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryFreeCompany => new ActionMetadata("Temporarily Switch Chat Mode to Free Company", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryPvpTeam => new ActionMetadata("Temporarily Switch Chat Mode to PvP Team", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryNextCrossworldLinkshell => new ActionMetadata("Temporarily Switch Chat Mode to Next Cross-World LS", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryPreviousCrossworldLinkshell => new ActionMetadata("Temporarily Switch Chat Mode To Previous Cross-World LS", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryCrossWorldLinkshell1 => new ActionMetadata("Temporarily Switch Chat Mode To Cross-World LS 1", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryCrossWorldLinkshell2 => new ActionMetadata("Temporarily Switch Chat Mode To Cross-World LS 2", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryCrossWorldLinkshell3 => new ActionMetadata("Temporarily Switch Chat Mode To Cross-World LS 3", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryCrossWorldLinkshell4 => new ActionMetadata("Temporarily Switch Chat Mode To Cross-World LS 4", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryCrossWorldLinkshell5 => new ActionMetadata("Temporarily Switch Chat Mode To Cross-World LS 5", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryCrossWorldLinkshell6 => new ActionMetadata("Temporarily Switch Chat Mode To Cross-World LS 6", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryCrossWorldLinkshell7 => new ActionMetadata("Temporarily Switch Chat Mode To Cross-World LS 7", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryCrossWorldLinkshell8 => new ActionMetadata("Temporarily Switch Chat Mode To Cross-World LS 8", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryNextLinkshell => new ActionMetadata("Temporarily Switch Chat Mode To Next Linkshell", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryPreviousLinkshell => new ActionMetadata("Temporarily Switch Chat Mode To Previous Linkshell", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryLinkshell1 => new ActionMetadata("Temporarily Switch Chat Mode To Linkshell 1", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryLinkshell2 => new ActionMetadata("Temporarily Switch Chat Mode To Linkshell 2", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryLinkshell3 => new ActionMetadata("Temporarily Switch Chat Mode To Linkshell 3", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryLinkshell4 => new ActionMetadata("Temporarily Switch Chat Mode To Linkshell 4", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryLinkshell5 => new ActionMetadata("Temporarily Switch Chat Mode To Linkshell 5", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryLinkshell6 => new ActionMetadata("Temporarily Switch Chat Mode To Linkshell 6", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryLinkshell7 => new ActionMetadata("Temporarily Switch Chat Mode To Linkshell 7", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryLinkshell8 => new ActionMetadata("Temporarily Switch Chat Mode To Linkshell 8", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),
            ChatChannels.TemporaryNoviceNetwork => new ActionMetadata("Temporarily Switch Chat Mode To Novice Network", ActionCategory.Chat, false, "Current implementation does not revert chat back to the original mode."),

            ChatChannels.ReplyForward => new ActionMetadata("Reply", ActionCategory.Chat, false, "Implementing Tells via ClientStructs are a pain."),
            ChatChannels.ReplyBack => new ActionMetadata("Reply (Back)", ActionCategory.Chat, false, "Implementing Tells via ClientStructs are a pain."),
            ChatChannels.Say => new ActionMetadata("Switch Chat Mode To Say", ActionCategory.Chat),
            ChatChannels.Yell => new ActionMetadata("Switch Chat Mode To Yell", ActionCategory.Chat),
            ChatChannels.Shout => new ActionMetadata("Switch Chat Mode To Shout", ActionCategory.Chat),
            ChatChannels.Party => new ActionMetadata("Switch Chat Mode To Party", ActionCategory.Chat),
            ChatChannels.Alliance => new ActionMetadata("Switch Chat Mode To Alliance", ActionCategory.Chat),
            ChatChannels.FreeCompany => new ActionMetadata("Switch Chat Mode To Free Company", ActionCategory.Chat),
            ChatChannels.PvpTeam => new ActionMetadata("Switch Chat Mode To PvP Team", ActionCategory.Chat),
            ChatChannels.NextCrossworldLinkshell => new ActionMetadata("Switch Chat Mode To Next Cross-World LS", ActionCategory.Chat),
            ChatChannels.PreviousCrossworldLinkshell => new ActionMetadata("Switch Chat Mode To Previous Cross-World LS", ActionCategory.Chat),
            ChatChannels.CrossWorldLinkshell1 => new ActionMetadata("Switch Chat Mode To Cross-World LS 1", ActionCategory.Chat),
            ChatChannels.CrossWorldLinkshell2 => new ActionMetadata("Switch Chat Mode To Cross-World LS 2", ActionCategory.Chat),
            ChatChannels.CrossWorldLinkshell3 => new ActionMetadata("Switch Chat Mode To Cross-World LS 3", ActionCategory.Chat),
            ChatChannels.CrossWorldLinkshell4 => new ActionMetadata("Switch Chat Mode To Cross-World LS 4", ActionCategory.Chat),
            ChatChannels.CrossWorldLinkshell5 => new ActionMetadata("Switch Chat Mode To Cross-World LS 5", ActionCategory.Chat),
            ChatChannels.CrossWorldLinkshell6 => new ActionMetadata("Switch Chat Mode To Cross-World LS 6", ActionCategory.Chat),
            ChatChannels.CrossWorldLinkshell7 => new ActionMetadata("Switch Chat Mode To Cross-World LS 7", ActionCategory.Chat),
            ChatChannels.CrossWorldLinkshell8 => new ActionMetadata("Switch Chat Mode To Cross-World LS 8", ActionCategory.Chat),
            ChatChannels.NextLinkshell => new ActionMetadata("Switch Chat Mode To Next Linkshell", ActionCategory.Chat),
            ChatChannels.PreviousLinkshell => new ActionMetadata("Switch Chat Mode To Previous Linkshell", ActionCategory.Chat),
            ChatChannels.Linkshell1 => new ActionMetadata("Switch Chat Mode To Linkshell 1", ActionCategory.Chat),
            ChatChannels.Linkshell2 => new ActionMetadata("Switch Chat Mode To Linkshell 2", ActionCategory.Chat),
            ChatChannels.Linkshell3 => new ActionMetadata("Switch Chat Mode To Linkshell 3", ActionCategory.Chat),
            ChatChannels.Linkshell4 => new ActionMetadata("Switch Chat Mode To Linkshell 4", ActionCategory.Chat),
            ChatChannels.Linkshell5 => new ActionMetadata("Switch Chat Mode To Linkshell 5", ActionCategory.Chat),
            ChatChannels.Linkshell6 => new ActionMetadata("Switch Chat Mode To Linkshell 6", ActionCategory.Chat),
            ChatChannels.Linkshell7 => new ActionMetadata("Switch Chat Mode To Linkshell 7", ActionCategory.Chat),
            ChatChannels.Linkshell8 => new ActionMetadata("Switch Chat Mode To Linkshell 8", ActionCategory.Chat),
            ChatChannels.NoviceNetwork => new ActionMetadata("Switch Chat Mode To Novice Network", ActionCategory.Chat),
            _ => throw new ArgumentOutOfRangeException(nameof(channel), channel, null)
        };
        public static (int channelType, uint? linkshellIdx, bool isPermanent) GetExecutionData(this ChatChannels channel) => channel switch
        {
            ChatChannels.ReplyForward => (-1, null, true),
            ChatChannels.ReplyBack => (-1, null, true),
            ChatChannels.NextCrossworldLinkshell => (-1, null, true),
            ChatChannels.PreviousCrossworldLinkshell => (-1, null, true),
            ChatChannels.NextLinkshell => (-1, null, true),
            ChatChannels.PreviousLinkshell => (-1, null, true),

            ChatChannels.Say => (1, null, true),
            ChatChannels.Yell => (4, null, true),
            ChatChannels.Shout => (5, null, true),
            ChatChannels.Party => (2, null, true),
            ChatChannels.Alliance => (3, null, true),
            ChatChannels.FreeCompany => (6, null, true),
            ChatChannels.PvpTeam => (7, null, true),
            ChatChannels.NoviceNetwork => (8, null, true),
            ChatChannels.Linkshell1 => (19, 0, true),
            ChatChannels.Linkshell2 => (20, 1, true),
            ChatChannels.Linkshell3 => (21, 2, true),
            ChatChannels.Linkshell4 => (22, 3, true),
            ChatChannels.Linkshell5 => (23, 4, true),
            ChatChannels.Linkshell6 => (24, 5, true),
            ChatChannels.Linkshell7 => (25, 6, true),
            ChatChannels.Linkshell8 => (26, 7, true),
            ChatChannels.CrossWorldLinkshell1 => (9, 0, true),
            ChatChannels.CrossWorldLinkshell2 => (10, 1, true),
            ChatChannels.CrossWorldLinkshell3 => (11, 2, true),
            ChatChannels.CrossWorldLinkshell4 => (12, 3, true),
            ChatChannels.CrossWorldLinkshell5 => (13, 4, true),
            ChatChannels.CrossWorldLinkshell6 => (14, 5, true),
            ChatChannels.CrossWorldLinkshell7 => (15, 6, true),
            ChatChannels.CrossWorldLinkshell8 => (16, 7, true),

            ChatChannels.TemporaryReplyForward => (-1, null, false),
            ChatChannels.TemporaryReplyBack => (-1, null, false),
            ChatChannels.TemporaryNextCrossworldLinkshell => (-1, null, false),
            ChatChannels.TemporaryPreviousCrossworldLinkshell => (-1, null, false),
            ChatChannels.TemporaryNextLinkshell => (-1, null, false),
            ChatChannels.TemporaryPreviousLinkshell => (-1, null, false),

            ChatChannels.TemporarySay => (1, null, false),
            ChatChannels.TemporaryYell => (4, null, false),
            ChatChannels.TemporaryShout => (5, null, false),
            ChatChannels.TemporaryParty => (2, null, false),
            ChatChannels.TemporaryAlliance => (3, null, false),
            ChatChannels.TemporaryFreeCompany => (6, null, false),
            ChatChannels.TemporaryPvpTeam => (7, null, false),
            ChatChannels.TemporaryNoviceNetwork => (8, null, false),
            ChatChannels.TemporaryLinkshell1 => (19, 0, false),
            ChatChannels.TemporaryLinkshell2 => (20, 1, false),
            ChatChannels.TemporaryLinkshell3 => (21, 2, false),
            ChatChannels.TemporaryLinkshell4 => (22, 3, false),
            ChatChannels.TemporaryLinkshell5 => (23, 4, false),
            ChatChannels.TemporaryLinkshell6 => (24, 5, false),
            ChatChannels.TemporaryLinkshell7 => (25, 6, false),
            ChatChannels.TemporaryLinkshell8 => (26, 7, false),
            ChatChannels.TemporaryCrossWorldLinkshell1 => (9, 0, false),
            ChatChannels.TemporaryCrossWorldLinkshell2 => (10, 1, false),
            ChatChannels.TemporaryCrossWorldLinkshell3 => (11, 2, false),
            ChatChannels.TemporaryCrossWorldLinkshell4 => (12, 3, false),
            ChatChannels.TemporaryCrossWorldLinkshell5 => (13, 4, false),
            ChatChannels.TemporaryCrossWorldLinkshell6 => (14, 5, false),
            ChatChannels.TemporaryCrossWorldLinkshell7 => (15, 6, false),
            ChatChannels.TemporaryCrossWorldLinkshell8 => (16, 7, false),
            _ => throw new ArgumentOutOfRangeException(nameof(channel), channel, null)
        };
    }
}
